# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np
print("Версия numpy:", np.__version__)


Версия numpy: 1.26.4


2) Создать нулевой вектор размера 10

In [2]:
zero = np.zeros(10)
print("Нулевой вектор размера 10:", zero)

Нулевой вектор размера 10: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [3]:
seven = np.full(7, 7)
print("Вектор, заполненный семерками размера 7:", seven)

Вектор, заполненный семерками размера 7: [7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [4]:
vector = np.arange(10, 101, 2)
print("Вектор, заполненный четными числами от 10 до 100:", vector)

Вектор, заполненный четными числами от 10 до 100: [ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [11]:
random_array = np.random.randint(1, 11, size=10)
reversed_array = random_array[::-1]
print("Случайный массив (числа от 1 до 10):", random_array)
print("Развернутый массив:", reversed_array)


Случайный массив (числа от 1 до 10): [ 2  6  5  5  1  3  2 10  6  4]
Развернутый массив: [ 4  6 10  2  3  1  5  5  6  2]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [6]:
matrix = np.arange(9).reshape(3, 3)
print("Матрица 3x3, заполненная числами от 0 до 9:")
print(matrix)

Матрица 3x3, заполненная числами от 0 до 9:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [7]:
matrix = np.eye(4, k=1)
print("Матрица 4x4 с единицами на диагонали, смещенной на один вверх:")
print(matrix)

Матрица 4x4 с единицами на диагонали, смещенной на один вверх:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [8]:
matrix_7_fill = np.full((4, 4), 7)  # Матрица 4x4 заполненная семерками
np.fill_diagonal(matrix_7_fill, [1, 2, 3, 4])  # Заполняем диагональ числами от 1 до 4
print("Матрица с числами от 1 до 4 по диагонали, остальное заполнено семерками:")
print(matrix_7_fill)


Матрица с числами от 1 до 4 по диагонали, остальное заполнено семерками:
[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [9]:
matrix_5x5 = np.tile(np.arange(5), (5, 1))
print("Матрица 5x5, заполненная числами от 0 до 4 по строкам:")
print(matrix_5x5)

Матрица 5x5, заполненная числами от 0 до 4 по строкам:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [12]:
matrix_random_10x10 = np.random.randint(1, 11, size=(10, 10))
matrix_centered_by_rows = matrix_random_10x10 - matrix_random_10x10.mean(axis=1, keepdims=True)
print("Матрица 10x10 (числа от 1 до 10), из которой вычтено среднее по строкам:")
print(matrix_centered_by_rows)


Матрица 10x10 (числа от 1 до 10), из которой вычтено среднее по строкам:
[[-1.8  3.2 -3.8  4.2  2.2  0.2 -0.8 -2.8 -0.8  0.2]
 [-1.1  3.9  3.9  0.9 -5.1 -4.1  2.9  0.9 -4.1  1.9]
 [-0.7  1.3  4.3 -4.7 -0.7  0.3  3.3  2.3 -2.7 -2.7]
 [ 5.   1.  -2.  -2.   3.   0.  -2.   1.  -2.  -2. ]
 [ 4.2 -1.8 -3.8 -2.8  1.2  0.2  4.2 -0.8 -2.8  2.2]
 [ 2.6  0.6  3.6 -1.4 -0.4  1.6 -0.4 -1.4 -1.4 -3.4]
 [-3.1 -1.1 -3.1  1.9  1.9 -1.1  3.9  4.9 -2.1 -2.1]
 [ 3.9  0.9  1.9 -3.1 -4.1  1.9 -0.1 -0.1  2.9 -4.1]
 [ 3.6 -3.4 -3.4  3.6  3.6  4.6 -0.4 -2.4 -3.4 -2.4]
 [ 3.8 -5.2  3.8  0.8  0.8 -1.2  1.8 -1.2 -0.2 -3.2]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [14]:
matrix_random_10x10_2 = np.random.randint(1, 11, size=(10, 10))
matrix_centered_by_columns = matrix_random_10x10_2 - np.median(matrix_random_10x10_2, axis=0, keepdims=True)
print("Матрица 10x10 (числа от 1 до 10), из которой вычтена медиана по столбцам:")
print(matrix_centered_by_columns)

Матрица 10x10 (числа от 1 до 10), из которой вычтена медиана по столбцам:
[[ 2.   0.  -1.5  1.  -0.5 -1.5 -3.   3.5  4.  -7.5]
 [ 0.  -2.  -4.5 -2.   5.5 -2.5 -3.   0.5 -4.  -4.5]
 [ 0.   0.  -2.5  2.  -0.5  0.5  4.  -2.5  0.   1.5]
 [-1.  -5.  -0.5 -5.   0.5 -0.5  0.   2.5 -1.   0.5]
 [-3.  -6.   1.5 -7.   1.5  2.5 -2.  -4.5  3.   1.5]
 [-4.   1.   0.5  0.  -3.5  2.5  0.   2.5  0.  -4.5]
 [ 0.   1.  -1.5  1.   1.5 -4.5  4.  -0.5  3.   0.5]
 [ 1.  -4.   2.5 -5.  -1.5 -3.5 -4.  -0.5  3.  -0.5]
 [-6.   0.   2.5  0.   4.5  2.5  0.  -3.5 -2.   1.5]
 [ 1.   0.   0.5  0.  -2.5  2.5  3.   0.5 -2.  -1.5]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [16]:
# Создаем матрицу случайных чисел от 1 до 10 размера 5x5
matrix_random_5x5 = np.random.randint(1, 11, size=(5, 5))
# Находим максимум и минимум по строкам и добавляем как столбцы
max_columns = matrix_random_5x5.max(axis=1).reshape(-1, 1)
min_columns = matrix_random_5x5.min(axis=1).reshape(-1, 1)
# Добавляем столбцы максимумов и минимумов к исходной матрице
matrix_extended = np.hstack((matrix_random_5x5, max_columns, min_columns))
print("Матрица 5x5 (числа от 1 до 10) с добавленными столбцами максимумов и минимумов по строкам:")
print(matrix_extended)

Матрица 5x5 (числа от 1 до 10) с добавленными столбцами максимумов и минимумов по строкам:
[[ 8  4  2  1  2  8  1]
 [ 5 10  1  8  7 10  1]
 [10  2  4  3  3 10  2]
 [ 4  7  4  3  7  7  3]
 [ 2 10 10  6  5 10  2]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [17]:
# Создаем вектор чисел от 1 до 51
vector_1_to_51 = np.arange(1, 52)

# Преобразуем вектор в вектор нечетных чисел и в вектор четных чисел
odd_vector = vector_1_to_51[vector_1_to_51 % 2 != 0].reshape(-1, 1)  # Нечетные числа, преобразованные в столбец
even_vector = vector_1_to_51[vector_1_to_51 % 2 == 0].reshape(1, -1)  # Четные числа, преобразованные в строку

# Находим произведение этих матриц
matrix_product = np.dot(odd_vector, even_vector)
print("Произведение матриц из четных и нечетных чисел:")
print(matrix_product)

# Находим обратную матрицу этого произведения
inverse_matrix = np.linalg.inv(matrix_product)
print("Обратная матрица произведения:")
print(inverse_matrix)

Произведение матриц из четных и нечетных чисел:
[[   2    4    6    8   10   12   14   16   18   20   22   24   26   28
    30   32   34   36   38   40   42   44   46   48   50]
 [   6   12   18   24   30   36   42   48   54   60   66   72   78   84
    90   96  102  108  114  120  126  132  138  144  150]
 [  10   20   30   40   50   60   70   80   90  100  110  120  130  140
   150  160  170  180  190  200  210  220  230  240  250]
 [  14   28   42   56   70   84   98  112  126  140  154  168  182  196
   210  224  238  252  266  280  294  308  322  336  350]
 [  18   36   54   72   90  108  126  144  162  180  198  216  234  252
   270  288  306  324  342  360  378  396  414  432  450]
 [  22   44   66   88  110  132  154  176  198  220  242  264  286  308
   330  352  374  396  418  440  462  484  506  528  550]
 [  26   52   78  104  130  156  182  208  234  260  286  312  338  364
   390  416  442  468  494  520  546  572  598  624  650]
 [  30   60   90  120  150  180  210  240 

LinAlgError: Last 2 dimensions of the array must be square

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [18]:
# Создаем 8x8 матрицу и заполняем её в шахматном порядке нулями и единицами
chessboard_matrix = np.zeros((8, 8), dtype=int)
chessboard_matrix[1::2, ::2] = 1  # Заполняем единицами каждую вторую строку с каждого второго столбца
chessboard_matrix[::2, 1::2] = 1  # Заполняем единицами каждую первую строку с каждого второго столбца
print("8x8 матрица, заполненная в шахматном порядке:")
print(chessboard_matrix)

8x8 матрица, заполненная в шахматном порядке:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
